### PR TITLE
make example work

### PR DESCRIPTION
**Pull request by RayProud**
Fixed an example in README.md.

-  changed `then` to `next` (just like in `example` folder)
-  changed `text` type to `list`, because `text` type isn't implemented yet

### CODE REVIEW

**Comment by RayProud** [comment]
Hey! No, I'm no sure `next` is the better choice. 
I'll fix `Wizard.js` and examples.

**Comment by AaronGillBraun** [comment]
Alright great!

**Comment by RayProud** [comment]
@AaronGillBraun, hey!

I did some fixes but the only thing I could't handle is that the app didn't stop listening stdin so I had to exit process in `example/src/index.js`.

Maybe you have any ideas how to work it out in `Wizard.js`?

**Comment by AaronGillBraun** [comment]
Thanks for the fixes. I'm not sure what you mean by "wont stop listening to stdin". I can run the example as is and I can kill it using `ctrl-c`. It could be a platform specific problem...? (I'm on macOS).  I wouldn't be surprised. I haven't actually done anything with this in a while and only intended to use it in another project I was working on.

I would be happy to pick this back up and change some things around, implement the final basic components and have a fully working library. The stuff you have looks good so I'll merge it and fix some of the things when I've got time this week. And, if you can give me the steps to reproduce the problem, that'd be great.

Thanks a lot!

**Comment by RayProud** [comment]
Hey!
The problem was that the after you did all steps the process didn't terminate. So I had to use `process.exit` by myself in the example.

- fixed this problem. You can see `stopListeningReadline` after all traverses;
- fixed ctrl+c bug — now components remove a data listener before resolve values. And the only place where we start listening to ESC and ctrl+c is `init` of `Wizard`.

I'm still not sure about some code repeating in different components (like removing a data listener in `handleOnData`s) but it works for now. Let it be my homework. Unless you have any ideas how to make it better.

**Comment by RayProud** [comment]
> I would be happy to pick this back up and change some things around, implement the final basic components and have a fully working library.

If you don't mind I'd like to implement `text` type component and create another PR with it.

**Comment by RayProud** [comment]
I think this PR is ready to be tested.
Text type will be in another one.

**Comment by RayProud** [comment]
So, if everything works fine, merge this PR when you can.

**Comment by AaronGillBraun** [comment]
Looks good! While reviewing, I found some things that, while unrelated to your PR, should probably be changed before another one (like `/example/build` should not be in the repo). That way PR's won't be full diff's of transpiled files. Thanks a lot.

**Comment by RayProud** [comment]
Thanks for merging my PR!

Ok, I'm almost done with `text` type. I'l remove `build` from repo in the next PR.

**Comment by RayProud** [comment]
> Ok,  I'm almost done with text type. I'l remove build from repo in the next PR.

You already did it! Cool!

**Comment by AaronGillBraun** [comment]
Oh. I hope its not too big a problem. I spent today making some big changes to the repo. You should check out my latest commits. I fixed a ton of problems with it and made some slight API changes. It's a huge step-up from before. Hopefully you can easily port over your text component to the new API. To be honest, it might be easier considering the API changes make certain things much simpler.

**Comment by RayProud** [comment]
I'm sure it won't be a problem.

I'll look at your last commit.

**Pull request merged**
